@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjMxMDAwMTR9.oDl-VI0hPMzdm7T_Ll_zbQm2EUg31gppzjF4BTNQ-2M

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "kadeillianmt@gmail.com",
  "password": "password"
}

### Create Blog Post
POST http://localhost:3000/blog/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "hello",
  "author": "kade illian"
}


