
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "kadeillianmt@gmail.com",
  "password": "password"
}

### Create Blog Post
POST http://localhost:3000/blog/create
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "hello",
  "author": "kade illian"
}


